export const institutions = [
  'Mehran University of Engineering and Technology (MUET)',
  'University of Sindh',
  'NED University of Engineering and Technology',
  'Sindh Agriculture University',
  'Liaquat University of Medical and Health Sciences',
  'Shah Abdul Latif University Khairpur',
  'Sukkur IBA University',
  'Quaid-e-Awam University of Engineering, Science and Technology',
  'Sindh Madressatul Islam University',
  'Shaheed Benazir Bhutto University',
  'Benazir Bhutto Shaheed University of Technology and Skill Development',
  'Dawood University of Engineering and Technology',
  'Institute of Business Administration (IBA) Karachi',
  'Institute of Business Management (IoBM)',
  'Iqra University',
  'Jinnah University for Women',
  'Hamdard University',
  'SZABIST',
  'Sir Syed University of Engineering and Technology',
  'Greenwich University',
  'Bahria University Karachi',
  'Dow University of Health Sciences',
  'Jinnah Sindh Medical University',
  'Karachi University',
  'Federal Urdu University',
  'Hayat College',
  'Government College University Hyderabad',
  'D.J. Science College',
  'S.M. Law College',
  'Govt. National College',
  'Other',
];

export const departments = [
  'BE Computer Systems Engineering',
  'BE Software Engineering',
  'BS Computer Science (BSCS)',
  'BE Electronic Engineering',
  'BE Electrical Engineering',
  'BE Telecommunication Engineering',
  'BE Mechanical Engineering',
  'BE Civil Engineering',
  'BE Industrial Engineering & Management',
  'BE Chemical Engineering',
  'BE Materials Engineering',
  'BE Petroleum & Gas Engineering',
  'BE Metallurgical Engineering',
  'BE Energy & Environment Engineering',
  'BE Automotive Engineering',
  'BE Biomedical Engineering',
  'Architecture',
  'City & Regional Planning',
  'BS Mathematics',
  'BS Physics',
  'BS Chemistry',
  'Other',
];

export const committees = [
  'United Nations Security Council (UNSC)',
  'United Nations Human Rights Council (UNHRC)',
  'United Nations General Assembly (UNGA)',
  'United Nations Environment Programme (UNEP)',
  'World Health Organization (WHO)',
  'International Court of Justice (ICJ)',
  'Economic and Social Council (ECOSOC)',
  'Disarmament and International Security Committee (DISEC)',
];
